# ----------------------------
# Makefile Options
# ----------------------------

NAME = NEON
ICON = src/assets/neon16x16.png
DESCRIPTION = Neon interpreter
COMPRESSED = NO
COMPRESSED_MODE = zx7
CFLAGS = -Oz
LTO = NO

# ----------------------------

#include $(shell cedev-config --makefile)
include app_tools/makefile
