# ----------------------------
# Makefile Options
# ----------------------------

NAME = NEON
ICON = src/assets/neon16x16.png
DESCRIPTION = "Neon interpreter"
COMPRESSED = YES
COMPRESSED_MODE = zx7
CFLAGS = -Oz

# ----------------------------

include $(shell cedev-config --makefile)
