# ----------------------------
# Makefile Options
# ----------------------------

NAME = Neon
ICON = src/assets/neon16x16.png
DESCRIPTION = Neon interpreter
APPLICATION_DESCRIPTION = Neon interpreter
APPLICATION = YES
COMPRESSED = NO
COMPRESSED_MODE = zx7
CFLAGS = -Os
LTO = YES

# ----------------------------

include $(shell cedev-config --makefile)
