valgrind ../Compilés/Neon tests/ackermann.ne
valgrind ../Compilés/Neon tests/arbres.ne
valgrind ../Compilés/Neon tests/atomic.ne
valgrind ../Compilés/Neon tests/cmplx.ne
valgrind ../Compilés/Neon tests/dico.ne
valgrind ../Compilés/Neon tests/error_parallel.ne
valgrind ../Compilés/Neon tests/join.ne
valgrind ../Compilés/Neon tests/liste-n-ieme.ne
valgrind ../Compilés/Neon tests/local_parallel.ne
valgrind ../Compilés/Neon tests/mat.ne
valgrind ../Compilés/Neon tests/parallel.ne
valgrind ../Compilés/Neon tests/premiers.ne
valgrind ../Compilés/Neon tests/queue.ne
valgrind ../Compilés/Neon tests/stack.ne
