/*
 * This file is automatically generated. Don't modify it manually
 */
#include "headers/wordautomaton.h"

static const uint8_t final_states[] = {
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    WA_KEYWORD,
    WA_KEYWORD,
    0,
    0,
    WA_KEYWORD,
    0,
    0,
    0,
    WA_KEYWORD,
    0,
    WA_OPERATOR,
    0,
    WA_OPERATOR,
    0,
    0,
    WA_OPERATOR,
    0,
    0,
    WA_OPERATOR,
    WA_OPERATOR,
    0,
    WA_OPERATOR,
    0,
    0,
    0,
    0,
    0,
    WA_OPERATOR,
    WA_OPERATOR
};

static uint8_t (*states_functions[])(char) = {
    jump_start,
    jump_none,
    jump_s1,
    jump_s2,
    jump_s3,
    jump_s4,
    jump_s5,
    jump_s6,
    jump_s7,
    jump_s8,
    jump_s9,
    jump_s10,
    jump_s11,
    jump_s12,
    jump_s13,
    jump_s14,
    jump_s15,
    jump_s16,
    jump_s17,
    jump_s18,
    jump_s19,
    jump_s20,
    jump_s21,
    jump_s22,
    jump_s23,
    jump_s24,
    jump_s25,
    jump_s26,
    jump_s27,
    jump_s28,
    jump_s29,
    jump_s30,
    jump_s31,
    jump_s32,
    jump_s33,
    jump_s34,
    jump_s35,
    jump_s36,
    jump_s37,
    jump_s38,
    jump_s39,
    jump_s40,
    jump_s41,
    jump_s42,
    jump_s43,
    jump_s44,
    jump_s45,
    jump_s46,
    jump_s47,
    jump_s48,
    jump_s49,
    jump_s50,
    jump_s51,
    jump_s52,
    jump_s53,
    jump_s54,
    jump_s55,
    jump_s56,
    jump_s57,
    jump_s58,
    jump_s59,
    jump_s60,
    jump_s61,
    jump_s62,
    jump_s63,
    jump_s64,
    jump_s65,
    jump_s66,
    jump_s67,
    jump_s68,
    jump_s69,
    jump_s70,
    jump_s71,
    jump_s72,
    jump_s73,
    jump_s74,
    jump_s75,
    jump_s76,
    jump_s77,
    jump_s78,
    jump_s79,
    jump_s80,
    jump_s81,
    jump_s82,
    jump_s83,
    jump_s84,
    jump_s85,
    jump_s86,
    jump_s87,
    jump_s88,
    jump_s89,
    jump_s90,
    jump_s91,
    jump_s92,
    jump_s93,
    jump_s94,
    jump_s95,
    jump_s96,
    jump_s97,
    jump_s98,
    jump_s99,
    jump_s100,
    jump_s101,
    jump_s102,
    jump_s103,
    jump_s104,
    jump_s105,
    jump_s106,
    jump_s107,
    jump_s108,
    jump_s109,
    jump_s110,
    jump_s111,
    jump_s112,
    jump_s113,
    jump_s114,
    jump_s115
};

uint8_t jump_start(char c) {
    switch (c) {
        case 'i':
            return WA_S1;
        case 'w':
            return WA_S3;
        case 'f':
            return WA_S8;
        case 'r':
            return WA_S15;
        case 'l':
            return WA_S26;
        case 'a':
            return WA_S31;
        case 'd':
            return WA_S36;
        case 'm':
            return WA_S52;
        case 'c':
            return WA_S58;
        case 'b':
            return WA_S66;
        case 'p':
            return WA_S71;
        case 'T':
            return WA_S75;
        case 'F':
            return WA_S79;
        case 'N':
            return WA_S84;
        case 'e':
            return WA_S89;
        case 't':
            return WA_S92;
        case 'o':
            return WA_S98;
        case 'x':
            return WA_S100;
        case 'n':
            return WA_S103;
        case 'E':
            return WA_S107;
        default:
            return WA_NONE;
    }
}

uint8_t jump_none(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s1(char c) {
    switch (c) {
        case 'f':
            return WA_S2;
        case 'm':
            return WA_S21;
        case 'n':
            return WA_S42;
        case 's':
            return WA_S115;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s2(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s3(char c) {
    switch (c) {
        case 'h':
            return WA_S4;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s4(char c) {
    switch (c) {
        case 'i':
            return WA_S5;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s5(char c) {
    switch (c) {
        case 'l':
            return WA_S6;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s6(char c) {
    switch (c) {
        case 'e':
            return WA_S7;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s7(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s8(char c) {
    switch (c) {
        case 'o':
            return WA_S9;
        case 'u':
            return WA_S45;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s9(char c) {
    switch (c) {
        case 'r':
            return WA_S10;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s10(char c) {
    switch (c) {
        case 'e':
            return WA_S11;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s11(char c) {
    switch (c) {
        case 'a':
            return WA_S12;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s12(char c) {
    switch (c) {
        case 'c':
            return WA_S13;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s13(char c) {
    switch (c) {
        case 'h':
            return WA_S14;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s14(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s15(char c) {
    switch (c) {
        case 'e':
            return WA_S16;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s16(char c) {
    switch (c) {
        case 't':
            return WA_S17;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s17(char c) {
    switch (c) {
        case 'u':
            return WA_S18;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s18(char c) {
    switch (c) {
        case 'r':
            return WA_S19;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s19(char c) {
    switch (c) {
        case 'n':
            return WA_S20;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s20(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s21(char c) {
    switch (c) {
        case 'p':
            return WA_S22;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s22(char c) {
    switch (c) {
        case 'o':
            return WA_S23;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s23(char c) {
    switch (c) {
        case 'r':
            return WA_S24;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s24(char c) {
    switch (c) {
        case 't':
            return WA_S25;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s25(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s26(char c) {
    switch (c) {
        case 'o':
            return WA_S27;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s27(char c) {
    switch (c) {
        case 'c':
            return WA_S28;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s28(char c) {
    switch (c) {
        case 'a':
            return WA_S29;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s29(char c) {
    switch (c) {
        case 'l':
            return WA_S30;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s30(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s31(char c) {
    switch (c) {
        case 'w':
            return WA_S32;
        case 'n':
            return WA_S96;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s32(char c) {
    switch (c) {
        case 'a':
            return WA_S33;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s33(char c) {
    switch (c) {
        case 'i':
            return WA_S34;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s34(char c) {
    switch (c) {
        case 't':
            return WA_S35;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s35(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s36(char c) {
    switch (c) {
        case 'e':
            return WA_S37;
        case 'o':
            return WA_S88;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s37(char c) {
    switch (c) {
        case 'f':
            return WA_S38;
        case 'l':
            return WA_S106;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s38(char c) {
    switch (c) {
        case 'i':
            return WA_S39;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s39(char c) {
    switch (c) {
        case 'n':
            return WA_S40;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s40(char c) {
    switch (c) {
        case 'e':
            return WA_S41;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s41(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s42(char c) {
    switch (c) {
        case 'i':
            return WA_S43;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s43(char c) {
    switch (c) {
        case 't':
            return WA_S44;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s44(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s45(char c) {
    switch (c) {
        case 'n':
            return WA_S46;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s46(char c) {
    switch (c) {
        case 'c':
            return WA_S47;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s47(char c) {
    switch (c) {
        case 't':
            return WA_S48;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s48(char c) {
    switch (c) {
        case 'i':
            return WA_S49;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s49(char c) {
    switch (c) {
        case 'o':
            return WA_S50;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s50(char c) {
    switch (c) {
        case 'n':
            return WA_S51;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s51(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s52(char c) {
    switch (c) {
        case 'e':
            return WA_S53;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s53(char c) {
    switch (c) {
        case 't':
            return WA_S54;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s54(char c) {
    switch (c) {
        case 'h':
            return WA_S55;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s55(char c) {
    switch (c) {
        case 'o':
            return WA_S56;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s56(char c) {
    switch (c) {
        case 'd':
            return WA_S57;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s57(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s58(char c) {
    switch (c) {
        case 'o':
            return WA_S59;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s59(char c) {
    switch (c) {
        case 'n':
            return WA_S60;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s60(char c) {
    switch (c) {
        case 't':
            return WA_S61;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s61(char c) {
    switch (c) {
        case 'i':
            return WA_S62;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s62(char c) {
    switch (c) {
        case 'n':
            return WA_S63;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s63(char c) {
    switch (c) {
        case 'u':
            return WA_S64;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s64(char c) {
    switch (c) {
        case 'e':
            return WA_S65;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s65(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s66(char c) {
    switch (c) {
        case 'r':
            return WA_S67;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s67(char c) {
    switch (c) {
        case 'e':
            return WA_S68;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s68(char c) {
    switch (c) {
        case 'a':
            return WA_S69;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s69(char c) {
    switch (c) {
        case 'k':
            return WA_S70;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s70(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s71(char c) {
    switch (c) {
        case 'a':
            return WA_S72;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s72(char c) {
    switch (c) {
        case 's':
            return WA_S73;
        case 'r':
            return WA_S109;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s73(char c) {
    switch (c) {
        case 's':
            return WA_S74;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s74(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s75(char c) {
    switch (c) {
        case 'r':
            return WA_S76;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s76(char c) {
    switch (c) {
        case 'u':
            return WA_S77;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s77(char c) {
    switch (c) {
        case 'e':
            return WA_S78;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s78(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s79(char c) {
    switch (c) {
        case 'a':
            return WA_S80;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s80(char c) {
    switch (c) {
        case 'l':
            return WA_S81;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s81(char c) {
    switch (c) {
        case 's':
            return WA_S82;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s82(char c) {
    switch (c) {
        case 'e':
            return WA_S83;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s83(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s84(char c) {
    switch (c) {
        case 'o':
            return WA_S85;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s85(char c) {
    switch (c) {
        case 'n':
            return WA_S86;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s86(char c) {
    switch (c) {
        case 'e':
            return WA_S87;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s87(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s88(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s89(char c) {
    switch (c) {
        case 'n':
            return WA_S90;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s90(char c) {
    switch (c) {
        case 'd':
            return WA_S91;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s91(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s92(char c) {
    switch (c) {
        case 'h':
            return WA_S93;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s93(char c) {
    switch (c) {
        case 'e':
            return WA_S94;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s94(char c) {
    switch (c) {
        case 'n':
            return WA_S95;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s95(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s96(char c) {
    switch (c) {
        case 'd':
            return WA_S97;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s97(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s98(char c) {
    switch (c) {
        case 'r':
            return WA_S99;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s99(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s100(char c) {
    switch (c) {
        case 'o':
            return WA_S101;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s101(char c) {
    switch (c) {
        case 'r':
            return WA_S102;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s102(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s103(char c) {
    switch (c) {
        case 'o':
            return WA_S104;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s104(char c) {
    switch (c) {
        case 't':
            return WA_S105;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s105(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s106(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s107(char c) {
    switch (c) {
        case 'E':
            return WA_S108;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s108(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s109(char c) {
    switch (c) {
        case 'a':
            return WA_S110;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s110(char c) {
    switch (c) {
        case 'l':
            return WA_S111;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s111(char c) {
    switch (c) {
        case 'l':
            return WA_S112;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s112(char c) {
    switch (c) {
        case 'e':
            return WA_S113;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s113(char c) {
    switch (c) {
        case 'l':
            return WA_S114;
        default:
            return WA_NONE;
    }
}

uint8_t jump_s114(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t jump_s115(char c) {
    switch (c) {
        default:
            return WA_NONE;
    }
}

uint8_t wa_get_final(uint8_t state) {
    return final_states[state];
}

uint8_t wa_next_state(uint8_t state, char c) {
    return states_functions[state](c);
}

